const newsData = [
  {
    role: "all",
    src: "/assets/image/29.jpg",
    titleFirst: "전체-[플로깅 이야기]",
    titleSecond: "줍깅, 그게뭘까?",
    date: "2023.09.26",
  },
  {
    role: "all",
    src: "/assets/image/30.jpg",
    titleFirst: "전체-신재생에너지 사업,",
    titleSecond: "잘 되고 있는걸까?",
    date: "2023.09.26",
  },
  {
    role: "all",
    src: "/assets/image/31.jpg",
    titleFirst: "전체-병들어가는",
    titleSecond: "바다 이야기",
    date: "2023.09.26",
  },
  {
    role: "all",
    src: "/assets/image/29.jpg",
    titleFirst: "전체-[플로깅 이야기]",
    titleSecond: "줍깅, 그게뭘까?",
    date: "2023.09.26",
  },
  {
    role: "all",
    src: "/assets/image/30.jpg",
    titleFirst: "전체-신재생에너지 사업,",
    titleSecond: "잘 되고 있는걸까?",
    date: "2023.09.26",
  },
  {
    role: "all",
    src: "/assets/image/31.jpg",
    titleFirst: "전체-병들어가는",
    titleSecond: "바다 이야기",
    date: "2023.09.26",
  },
  {
    role: "all",
    src: "/assets/image/29.jpg",
    titleFirst: "전체-[플로깅 이야기]",
    titleSecond: "줍깅, 그게뭘까?",
    date: "2023.09.26",
  },
  {
    role: "all",
    src: "/assets/image/30.jpg",
    titleFirst: "전체-신재생에너지 사업,",
    titleSecond: "잘 되고 있는걸까?",
    date: "2023.09.26",
  },
  {
    role: "all",
    src: "/assets/image/31.jpg",
    titleFirst: "전체-병들어가는",
    titleSecond: "바다 이야기",
    date: "2023.09.26",
  },
  {
    role: "common",
    src: "/assets/image/29.jpg",
    titleFirst: "일반-[플로깅 이야기]",
    titleSecond: "줍깅, 그게뭘까?",
    date: "2023.09.26",
  },
  {
    role: "common",
    src: "/assets/image/30.jpg",
    titleFirst: "일반-신재생에너지 사업,",
    titleSecond: "잘 되고 있는걸까?",
    date: "2023.09.26",
  },
  {
    role: "common",
    src: "/assets/image/31.jpg",
    titleFirst: "일반-병들어가는",
    titleSecond: "바다 이야기",
    date: "2023.09.26",
  },
  {
    role: "common",
    src: "/assets/image/29.jpg",
    titleFirst: "일반-[플로깅 이야기]",
    titleSecond: "줍깅, 그게뭘까?",
    date: "2023.09.26",
  },
  {
    role: "common",
    src: "/assets/image/30.jpg",
    titleFirst: "일반-신재생에너지 사업,",
    titleSecond: "잘 되고 있는걸까?",
    date: "2023.09.26",
  },
  {
    role: "common",
    src: "/assets/image/31.jpg",
    titleFirst: "일반-병들어가는",
    titleSecond: "바다 이야기",
    date: "2023.09.26",
  },
  {
    role: "common",
    src: "/assets/image/29.jpg",
    titleFirst: "일반-[플로깅 이야기]",
    titleSecond: "줍깅, 그게뭘까?",
    date: "2023.09.26",
  },
  {
    role: "common",
    src: "/assets/image/30.jpg",
    titleFirst: "일반-신재생에너지 사업,",
    titleSecond: "잘 되고 있는걸까?",
    date: "2023.09.26",
  },
  {
    role: "common",
    src: "/assets/image/31.jpg",
    titleFirst: "일반-병들어가는",
    titleSecond: "바다 이야기",
    date: "2023.09.26",
  },
  {
    role: "common",
    src: "/assets/image/29.jpg",
    titleFirst: "일반-[플로깅 이야기]",
    titleSecond: "줍깅, 그게뭘까?",
    date: "2023.09.26",
  },
  {
    role: "common",
    src: "/assets/image/30.jpg",
    titleFirst: "일반-신재생에너지 사업,",
    titleSecond: "잘 되고 있는걸까?",
    date: "2023.09.26",
  },
  {
    role: "common",
    src: "/assets/image/31.jpg",
    titleFirst: "일반-병들어가는",
    titleSecond: "바다 이야기",
    date: "2023.09.26",
  },
  {
    role: "press",
    src: "/assets/image/29.jpg",
    titleFirst: "언론-[플로깅 이야기]",
    titleSecond: "줍깅, 그게뭘까?",
    date: "2023.09.26",
  },
  {
    role: "press",
    src: "/assets/image/30.jpg",
    titleFirst: "언론-신재생에너지 사업,",
    titleSecond: "잘 되고 있는걸까?",
    date: "2023.09.26",
  },
  {
    role: "press",
    src: "/assets/image/31.jpg",
    titleFirst: "언론-병들어가는",
    titleSecond: "바다 이야기",
    date: "2023.09.26",
  },
  {
    role: "press",
    src: "/assets/image/29.jpg",
    titleFirst: "언론-[플로깅 이야기]",
    titleSecond: "줍깅, 그게뭘까?",
    date: "2023.09.26",
  },
  {
    role: "press",
    src: "/assets/image/30.jpg",
    titleFirst: "언론-신재생에너지 사업,",
    titleSecond: "잘 되고 있는걸까?",
    date: "2023.09.26",
  },
  {
    role: "press",
    src: "/assets/image/31.jpg",
    titleFirst: "언론-병들어가는",
    titleSecond: "바다 이야기",
    date: "2023.09.26",
  },
  {
    role: "press",
    src: "/assets/image/29.jpg",
    titleFirst: "언론-[플로깅 이야기]",
    titleSecond: "줍깅, 그게뭘까?",
    date: "2023.09.26",
  },
  {
    role: "press",
    src: "/assets/image/30.jpg",
    titleFirst: "언론-신재생에너지 사업,",
    titleSecond: "잘 되고 있는걸까?",
    date: "2023.09.26",
  },
  {
    role: "press",
    src: "/assets/image/31.jpg",
    titleFirst: "언론-병들어가는",
    titleSecond: "바다 이야기",
    date: "2023.09.26",
  },
];

export default newsData;
